schema_version: 1

context:
  name: webstories
  version: 0.0.2

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/webstories-${{ version }}.tar.gz
  sha256: 0c46440f09d73cb43a7e1e9ebbe8b79d16bb02fb1f2d1d63f49cddf55886ddf0

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - beautifulsoup4 >=4.6,<5
    - bleach >=3.2,<4

tests:
  - python:
      imports:
        - webstories
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: Parser for AMP web stories
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/torchbox/webstories/

extra:
  recipe-maintainers:
    - rxm7706
